<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Table_stok extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Table_stok_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {

		$data = array(
            'content' => 'table_stok/table_stok_list',
        );
        $this->load->view('sb-admin', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Table_stok_model->json();
    }

    public function read($id) 
    {
        $row = $this->Table_stok_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_barang' => $row->id_barang,
		'total_barang' => $row->total_barang,
		'jenis_stok' => $row->jenis_stok,
	    );
            $data['content'] = 'table_stok/table_stok_read';

            $this->load->view('sb-admin', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('table_stok'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'content' => 'table_stok/table_stok_form', 
            'action' => site_url('table_stok/create_action'),
	    'id' => set_value('id'),
	    'id_barang' => set_value('id_barang'),
	    'total_barang' => set_value('total_barang'),
	    'jenis_stok' => set_value('jenis_stok'),
	    'barang' => $this->db->get('table_barang')->result(),
	);
        $this->load->view('sb-admin', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_barang' => $this->input->post('id_barang',TRUE),
		'total_barang' => $this->input->post('total_barang',TRUE),
		'jenis_stok' => $this->input->post('jenis_stok',TRUE),
	    );

            $this->Table_stok_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('table_stok'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Table_stok_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'content' => 'table_stok/table_stok_form',  
                'action' => site_url('table_stok/update_action'),
		'id' => set_value('id', $row->id),
		'id_barang' => set_value('id_barang', $row->id_barang),
		'total_barang' => set_value('total_barang', $row->total_barang),
		'jenis_stok' => set_value('jenis_stok', $row->jenis_stok),
		'barang' => $this->db->get('table_barang')->result(),
	    );
            $this->load->view('sb-admin', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('table_stok'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_barang' => $this->input->post('id_barang',TRUE),
		'total_barang' => $this->input->post('total_barang',TRUE),
		'jenis_stok' => $this->input->post('jenis_stok',TRUE),
	    );

            $this->Table_stok_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('table_stok'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Table_stok_model->get_by_id($id);

        if ($row) {
            $this->Table_stok_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('table_stok'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('table_stok'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_barang', 'id barang', 'trim|required');
	$this->form_validation->set_rules('total_barang', 'total barang', 'trim|required');
	$this->form_validation->set_rules('jenis_stok', 'jenis stok', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Table_stok.php */
/* Location: ./application/controllers/Table_stok.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-21 13:34:14 */
/* http://harviacode.com */
